set_property SRC_FILE_INFO {cfile:{E:/previous assignments/DigitalSystemsAndMicroprocessors/assignment2_revised/demos/Solutions/Solution3b/Solution3b.srcs/constrs_1/new/t1.xdc} rfile:../../../Solution3b.srcs/constrs_1/new/t1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells s4/memory_reg]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y6 [get_cells s4/memory_reg]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells s4/output_4_OBUF_inst_i_1]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y6 [get_cells s4/output_4_OBUF_inst_i_1]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB17 [get_cells output_4_OBUF_inst]
